VALID_AXES = ["x", "y"]
VALID_COLORS = ["rg", "rb", "br", "bg", "gr", "gb"]
VALID_FADE_FUNCTIONS = [
    "linear", "l",
    "ease_out", "eo",
    "ease_in_out", "eio"
]

DEFAULT_FADE_FUNCTION = "ease_in_out"

DEFAULT_OUTPUT = "default" # This is just a placeholder, not an actual filename.

DEFAULT_INVERT_GAMMA = 1.0
DEFAULT_INVERT_EVERY = 2
DEFAULT_INVERT_PAUSE = 0

DEFAULT_RGB_SHIFT_AXIS = "x"
DEFAULT_RGB_SHIFT_INTENSITY = 5
DEFAULT_RGB_SHIFT_COLORS = "rg"
DEFAULT_RGB_SHIFT_EVERY = 2
DEFAULT_RGB_SHIFT_PAUSE = 0

DEFAULT_SHAKE_AXIS = "x"
DEFAULT_SHAKE_AMPLITUDE = 10
DEFAULT_SHAKE_FREQUENCY = 1
DEFAULT_SHAKE_DAMPEN = 0.5
DEFAULT_SHAKE_BLUR = 0

MIN_ZOOM_FACTOR = 1.0
MAX_ZOOM_FACTOR = 10.0
DEFAULT_ZOOM_FACTOR = 2
DEFAULT_ZOOM_ALPHA = 0.5
# Those two are substituted in the filter function.
DEFAULT_ZOOM_CENTER_X = -1
DEFAULT_ZOOM_CENTER_Y = -1
DEFAULT_ZOOM_RELATIVE_MODE = False

DEFAULT_RANDOMIZER_MAX_FRAMES = 2

DEFAULT_AFTERIMAGES_START_WHITE = False
DEFAULT_AFTERIMAGES_AMOUNT = 1
DEFAULT_AFTERIMAGES_DELAY = 10
DEFAULT_AFTERIMAGES_ALPHA = 0.5

DEFAULT_SPEED_CHANGE_FACTOR = 1.0
DEFAULT_SPEED_CHANGE_PRESERVE_PITCH = False
DEFAULT_SPEED_CHANGE_PRESERVE_FORMANTS = False

MIN_EQ_CONTRAST_DARKEN = MIN_EQ_CONTRAST_LIGHTEN = -1000.0
MAX_EQ_CONTRAST_DARKEN = MAX_EQ_CONTRAST_LIGHTEN = 1000.0
DEFAULT_EQ_CONTRAST_DARKEN = DEFAULT_EQ_CONTRAST_LIGHTEN = 1.0

MIN_EQ_BRIGHTNESS_DARKEN = -1.0
MAX_EQ_BRIGHTNESS_DARKEN = 0.0
MIN_EQ_BRIGHTNESS_LIGHTEN = 0.0
MAX_EQ_BRIGHTNESS_LIGHTEN = 1.0
DEFAULT_EQ_BRIGHTNESS_DARKEN = DEFAULT_EQ_BRIGHTNESS_LIGHTEN = 0.0

MIN_EQ_SATURATION_DARKEN = MIN_EQ_SATURATION_LIGHTEN = 0.0
MAX_EQ_SATURATION_DARKEN = MAX_EQ_SATURATION_LIGHTEN = 3.0
DEFAULT_EQ_SATURATION_DARKEN = DEFAULT_EQ_SATURATION_LIGHTEN = 1.0

MIN_EQ_GAMMA_DARKEN = MIN_EQ_GAMMA_R_DARKEN = MIN_EQ_GAMMA_G_DARKEN = MIN_EQ_GAMMA_B_DARKEN = 1.0
MAX_EQ_GAMMA_DARKEN = MAX_EQ_GAMMA_R_DARKEN = MAX_EQ_GAMMA_G_DARKEN = MAX_EQ_GAMMA_B_DARKEN = 10.0
MIN_EQ_GAMMA_LIGHTEN = MIN_EQ_GAMMA_R_LIGHTEN = MIN_EQ_GAMMA_G_LIGHTEN  = MIN_EQ_GAMMA_B_LIGHTEN = 0.1
MAX_EQ_GAMMA_LIGHTEN = MAX_EQ_GAMMA_R_LIGHTEN = MAX_EQ_GAMMA_G_LIGHTEN = MAX_EQ_GAMMA_B_LIGHTEN = 1.0
DEFAULT_EQ_GAMMA_DARKEN = \
DEFAULT_EQ_GAMMA_LIGHTEN = \
DEFAULT_EQ_GAMMA_R_DARKEN = \
DEFAULT_EQ_GAMMA_G_DARKEN = \
DEFAULT_EQ_GAMMA_B_DARKEN = \
DEFAULT_EQ_GAMMA_R_LIGHTEN = \
DEFAULT_EQ_GAMMA_G_LIGHTEN = \
DEFAULT_EQ_GAMMA_B_LIGHTEN = 1.0

MIN_EQ_GAMMA_WEIGHT_DARKEN = MIN_EQ_GAMMA_WEIGHT_LIGHTEN = 0.0
MAX_EQ_GAMMA_WEIGHT_DARKEN = MAX_EQ_GAMMA_WEIGHT_LIGHTEN = 1.0
DEFAULT_EQ_GAMMA_WEIGHT_DARKEN = DEFAULT_EQ_GAMMA_WEIGHT_LIGHTEN = 1.0

MIN_HUE_SATURATION_HUE = -180.0
MAX_HUE_SATURATION_HUE = 180.0

MIN_HUE_SATURATION_SATURATION = -10.0
MAX_HUE_SATURATION_SATURATION = 10.0
DEFAULT_HUE_SATURATION_SATURATION = 1.0

MIN_HUE_SATURATION_BRIGHTNESS = -10.0
MAX_HUE_SATURATION_BRIGHTNESS = 10.0

DEFAULT_FADE_DURATION = 30
DEFAULT_FADE_COLOR = "black"

DEFAULT_GAUSSIAN_BLUR_SIGMA = 0.5
DEFAULT_GAUSSIAN_BLUR_STEPS = 1

## FFMPEG uses this as its upper bound.

UINT32_MAX = 4294967295
TRANSPARENT_FFMPEG_COLOR = "0xFFFFFF00"
