DEFAULT_OUTPUT = "default" # This is just a placeholder, not an actual filename.

DEFAULT_STROBE_EVERY = 2
DEFAULT_STROBE_PAUSE = 0

DEFAULT_RGB_SHIFT_INTENSITY = 5
DEFAULT_RGB_SHIFT_EVERY = 2
DEFAULT_RGB_SHIFT_PAUSE = 0

DEFAULT_ZOOM_FACTOR = 2
DEFAULT_ZOOM_CENTER_X = 0 # TODO : relative coordinates instead?
DEFAULT_ZOOM_CENTER_Y = 0
DEFAULT_ZOOM_ALPHA = 0.5
DEFAULT_ZOOM_EVERY = 1
DEFAULT_ZOOM_PAUSE = 0

## FFMPEG uses this as its upper bound.

UINT32_MAX = 4294967295
